### ISSUE TITLE
BigInt to use toString as its toJSON, to align with proposed Temporals

### ISSUE THREAD

**Issue by kaizhu256** [tc39/proposal-bigint#173] opened 2018-10-20 06:46 UTC
the champion wishes to align BigInt's JSON.stringify behavior with that of proposed temporal-objects (https://github.com/tc39/proposal-temporal/issues/74).  the two currently diverge:

- JSON.stringify on BigInt throws ```TypeError``` unless toJSON is explicitly defined by user

- JSON.stringify on Temporals behave like toString :
```javascript
JSON.stringify(CivilDate)     // '2017-12-31'
JSON.stringify(CivilTime)     // '17:00:00'
JSON.stringify(CivilDateTime) // '2017-12-31T12:00:00'
JSON.stringify(Instant)       // '2017-12-31T00:00:00Z'
JSON.stringify(ZonedInstant)  // '2017‑12‑31T09:00:00+09:00'
```

the options for changing JSON.stringify behaviors are:
1. keep divergent
2. align BigInt with Temporal (BigInt uses toString instead of throwing ```TypeError```)
3. align Temporal with BigInt (Temporal throws ```TypeError```)
4. BigInt does something else (e.g. JSONNumber - https://github.com/tc39/proposal-bigint/issues/162#issuecomment-409135023)

context:
- option 2 breaks current  BigInt spec, but champion is willing to reconsider (**_and why this issue was created_**)
- option 3 is opposed by Temporal folks
- option 4 was discussed multiple-times with no consensus

**Comment by littledan** [comment] 2018-10-20 09:57
I agree that we should be in alignment with Temporal. This needs to be a precondition for Temporal to go to Stage 3. I've made the case in that proposal's repository that it should copy BigInt's behavior.

Closing this issue as a duplicate of #162 .

**Closed by littledan** 2018-10-20 09:57 UTC
